# permissions for end users to edit flavors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flavor-editor-role
rules:
- apiGroups:
  - compute.onmetal.de
  resources:
  - flavors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.onmetal.de
  resources:
  - flavors/status
  verbs:
  - get
