# permissions for end users to view networkinterfaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networkinterface-viewer-role
rules:
- apiGroups:
  - network.onmetal.de
  resources:
  - networkinterfaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.onmetal.de
  resources:
  - networkinterfaces/status
  verbs:
  - get
