
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - compute.onmetal.de
  resources:
  - images
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.onmetal.de
  resources:
  - images/finalizers
  verbs:
  - update
- apiGroups:
  - compute.onmetal.de
  resources:
  - images/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - compute.onmetal.de
  resources:
  - machineclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.onmetal.de
  resources:
  - machineclasses/finalizers
  verbs:
  - update
- apiGroups:
  - compute.onmetal.de
  resources:
  - machineclasses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - compute.onmetal.de
  resources:
  - machinepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.onmetal.de
  resources:
  - machinepools/finalizers
  verbs:
  - update
- apiGroups:
  - compute.onmetal.de
  resources:
  - machinepools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - compute.onmetal.de
  resources:
  - sshpublickeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.onmetal.de
  resources:
  - sshpublickeys/finalizers
  verbs:
  - update
- apiGroups:
  - compute.onmetal.de
  resources:
  - sshpublickeys/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.onmetal.de
  resources:
  - accounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.onmetal.de
  resources:
  - accounts/finalizers
  verbs:
  - update
- apiGroups:
  - core.onmetal.de
  resources:
  - accounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.onmetal.de
  resources:
  - regions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.onmetal.de
  resources:
  - regions/finalizers
  verbs:
  - update
- apiGroups:
  - core.onmetal.de
  resources:
  - regions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.onmetal.de
  resources:
  - scopes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.onmetal.de
  resources:
  - scopes/finalizers
  verbs:
  - update
- apiGroups:
  - core.onmetal.de
  resources:
  - scopes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.onmetal.de
  resources:
  - storageclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.onmetal.de
  resources:
  - storageclasses/finalizers
  verbs:
  - update
- apiGroups:
  - storage.onmetal.de
  resources:
  - storageclasses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.onmetal.de
  resources:
  - storagepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.onmetal.de
  resources:
  - storagepools/finalizers
  verbs:
  - update
- apiGroups:
  - storage.onmetal.de
  resources:
  - storagepools/status
  verbs:
  - get
  - patch
  - update
