
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - compute.onmetal.de
  resources:
  - machineclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.onmetal.de
  resources:
  - machineclasses/finalizers
  verbs:
  - update
- apiGroups:
  - compute.onmetal.de
  resources:
  - machineclasses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - compute.onmetal.de
  resources:
  - machinepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.onmetal.de
  resources:
  - machinepools/finalizers
  verbs:
  - update
- apiGroups:
  - compute.onmetal.de
  resources:
  - machinepools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - compute.onmetal.de
  resources:
  - machines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.onmetal.de
  resources:
  - machines/finalizers
  verbs:
  - update
- apiGroups:
  - compute.onmetal.de
  resources:
  - machines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.onmetal.de
  resources:
  - clusterprefixallocations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.onmetal.de
  resources:
  - clusterprefixallocations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.onmetal.de
  resources:
  - clusterprefixes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.onmetal.de
  resources:
  - clusterprefixes/finalizers
  verbs:
  - update
- apiGroups:
  - network.onmetal.de
  resources:
  - clusterprefixes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.onmetal.de
  resources:
  - gateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.onmetal.de
  resources:
  - gateways/finalizers
  verbs:
  - update
- apiGroups:
  - network.onmetal.de
  resources:
  - gateways/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.onmetal.de
  resources:
  - ipamranges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.onmetal.de
  resources:
  - ipamranges/finalizers
  verbs:
  - update
- apiGroups:
  - network.onmetal.de
  resources:
  - ipamranges/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.onmetal.de
  resources:
  - ips
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.onmetal.de
  resources:
  - ips/finalizers
  verbs:
  - update
- apiGroups:
  - network.onmetal.de
  resources:
  - ips/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.onmetal.de
  resources:
  - prefixallocations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.onmetal.de
  resources:
  - prefixallocations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.onmetal.de
  resources:
  - prefixes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.onmetal.de
  resources:
  - prefixes/finalizers
  verbs:
  - update
- apiGroups:
  - network.onmetal.de
  resources:
  - prefixes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.onmetal.de
  resources:
  - reservedips
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.onmetal.de
  resources:
  - reservedips/finalizers
  verbs:
  - update
- apiGroups:
  - network.onmetal.de
  resources:
  - reservedips/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.onmetal.de
  resources:
  - routingdomains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.onmetal.de
  resources:
  - routingdomains/finalizers
  verbs:
  - update
- apiGroups:
  - network.onmetal.de
  resources:
  - routingdomains/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.onmetal.de
  resources:
  - securitygroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.onmetal.de
  resources:
  - securitygroups/finalizers
  verbs:
  - update
- apiGroups:
  - network.onmetal.de
  resources:
  - securitygroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.onmetal.de
  resources:
  - subnets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.onmetal.de
  resources:
  - subnets/finalizers
  verbs:
  - update
- apiGroups:
  - network.onmetal.de
  resources:
  - subnets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.onmetal.de
  resources:
  - storageclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.onmetal.de
  resources:
  - storageclasses/finalizers
  verbs:
  - update
- apiGroups:
  - storage.onmetal.de
  resources:
  - storageclasses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.onmetal.de
  resources:
  - storagepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.onmetal.de
  resources:
  - storagepools/finalizers
  verbs:
  - update
- apiGroups:
  - storage.onmetal.de
  resources:
  - storagepools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.onmetal.de
  resources:
  - volumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.onmetal.de
  resources:
  - volumeclaims/finalizers
  verbs:
  - update
- apiGroups:
  - storage.onmetal.de
  resources:
  - volumeclaims/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.onmetal.de
  resources:
  - volumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.onmetal.de
  resources:
  - volumes/finalizers
  verbs:
  - update
- apiGroups:
  - storage.onmetal.de
  resources:
  - volumes/status
  verbs:
  - get
  - patch
  - update
