apiVersion: networking.ironcore.dev/v1alpha1
kind: VirtualIP
metadata:
  name: virtualip-sample
spec:
  type: Public
  ipFamily: IPv4
#status:
#  ip: 10.0.0.1 # This will be populated by the corresponding controller.
