apiVersion: network.onmetal.de/v1alpha1
kind: SecurityGroup
metadata:
  name: sshaccess
  namespace: external-access
spec:
  ingress:
    - name: ssh
      action: allow # deny
      protocol: TCP # optional "*" if not set
      portRange:
        startPort: 22 # optional same as protocol
      source:
        cidr: 0.0.0.0/0
  egress:
    - name: externalaccess
      action: allow
      protocol: "*"
      destination:
        cidr: 0.0.0.0/0
status:
  state: Used
  message: "All good"
