#apiVersion: network.onmetal.de/v1alpha1
#kind: IPAMRange
#metadata:
#  name: parent
#spec:
#  cidrs:
#    - 10.0.0.0/16
#---
apiVersion: network.onmetal.de/v1alpha1
kind: IPAMRange
metadata:
  name: child
spec:
  parent:
    name: parent
  requests:
    - size: 17
      #---
      #apiVersion: network.onmetal.de/v1alpha1
      #kind: IPAMRange
      #metadata:
      #  name: grandchild
      #spec:
      #  parent:
      #    name: child
      #  requests:
      #    - size: 32
      #---
      #apiVersion: network.onmetal.de/v1alpha1
      #kind: IPAMRange
      #metadata:
      #  name: grandchild2
      #spec:
      #  parent:
      #    name: child
      #  requests:
      #    - size: 32
