apiVersion: networking.api.onmetal.de/v1alpha1
kind: NetworkInterface
metadata:
  name: networkinterface-sample
spec:
  networkRef:
    name: network-sample
  ipFamilies: [ IPv4 ]
  ips:
    - value: 10.0.0.1 # It is also possible to directly specify IPs without IPAM
  #    - value: 2607:f0d0:1002:51::4 # Same applies for v6 addresses
  #    - ephemeralIP:
  #        prefixTemplate
  #          spec:
  #            ipFamily: IPv4
  #            parentRef:
  #              name: my-node-prefix-v4
  #    - ephemeralIP:
  #        prefixTemplate
  #          spec:
  #            ipFamily: IPv6
  #            parentRef:
  #              name: my-node-prefix-v6
  machineRef:
    name: machine-sample
#status:
#  ips: # This will be updated with the allocated addresses.
#    - 10.0.0.1
#    - 2607:f0d0:1002:51::4
