# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
  - bases/compute.onmetal.de_machineclasses.yaml
  - bases/compute.onmetal.de_machinepools.yaml
  - bases/storage.onmetal.de_storagepools.yaml
  - bases/storage.onmetal.de_storageclasses.yaml
  - bases/storage.onmetal.de_volumes.yaml
  - bases/storage.onmetal.de_volumeattachments.yaml
  - bases/network.onmetal.de_reservedips.yaml
  - bases/network.onmetal.de_securitygroups.yaml
  - bases/network.onmetal.de_subnets.yaml
  - bases/compute.onmetal.de_machines.yaml
  - bases/network.onmetal.de_ipamranges.yaml
  - bases/network.onmetal.de_gateways.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
  # [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
  # patches here are for enabling the conversion webhook for each CRD
  #- patches/webhook_in_machineclasses.yaml
  #- patches/webhook_in_machinepools.yaml
  #- patches/webhook_in_storagepools.yaml
  #- patches/webhook_in_storageclasses.yaml
  #- patches/webhook_in_volumes.yaml
  #- patches/webhook_in_volumeattachments.yaml
  #- patches/webhook_in_reservedips.yaml
  #- patches/webhook_in_securitygroups.yaml
  #- patches/webhook_in_subnets.yaml
  #- patches/webhook_in_machines.yaml
  #- patches/webhook_in_routingdomain.yaml
  #- patches/webhook_in_ipamranges.yaml
  #- patches/webhook_in_gateways.yaml
  #+kubebuilder:scaffold:crdkustomizewebhookpatch

  # [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
  # patches here are for enabling the CA injection for each CRD
  - patches/cainjection_in_machineclasses.yaml
  - patches/cainjection_in_machinepools.yaml
  - patches/cainjection_in_storagepools.yaml
  - patches/cainjection_in_storageclasses.yaml
  - patches/cainjection_in_volumes.yaml
  - patches/cainjection_in_volumeattachments.yaml
  - patches/cainjection_in_reservedips.yaml
  - patches/cainjection_in_securitygroups.yaml
  - patches/cainjection_in_subnets.yaml
  - patches/cainjection_in_machines.yaml
  - patches/cainjection_in_ipamranges.yaml
  - patches/cainjection_in_gateways.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
  - kustomizeconfig.yaml
