# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/core.onmetal.de_accounts.yaml
- bases/core.onmetal.de_scopes.yaml
- bases/compute.onmetal.de_machineclasses.yaml
- bases/core.onmetal.de_regions.yaml
- bases/compute.onmetal.de_machinepools.yaml
- bases/storage.onmetal.de_storagepools.yaml
- bases/storage.onmetal.de_storageclasses.yaml
- bases/compute.onmetal.de_images.yaml
- bases/compute.onmetal.de_sshpublickeys.yaml
- bases/storage.onmetal.de_volumes.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_accounts.yaml
#- patches/webhook_in_scopes.yaml
#- patches/webhook_in_machineclasses.yaml
#- patches/webhook_in_regions.yaml
#- patches/webhook_in_machinepools.yaml
#- patches/webhook_in_storagepools.yaml
#- patches/webhook_in_storageclasses.yaml
#- patches/webhook_in_images.yaml
#- patches/webhook_in_sshpublickeys.yaml
#- patches/webhook_in_volumes.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_accounts.yaml
#- patches/cainjection_in_scopes.yaml
#- patches/cainjection_in_machineclasses.yaml
#- patches/cainjection_in_regions.yaml
#- patches/cainjection_in_machinepools.yaml
#- patches/cainjection_in_storagepools.yaml
#- patches/cainjection_in_storageclasses.yaml
#- patches/cainjection_in_images.yaml
#- patches/cainjection_in_sshpublickeys.yaml
#- patches/cainjection_in_volumes.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
