apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  namespace: system
  labels:
    control-plane: etcd
spec:
  selector:
    matchLabels:
      control-plane: etcd
  serviceName: etcd
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: etcd
      labels:
        control-plane: etcd
    spec:
      containers:
        - command:
            - etcd
          args:
            - -listen-client-urls=http://0.0.0.0:2379
            - -advertise-client-urls=http://localhost:2379
            - -data-dir=/etcd-data-dir/default.etcd
          image: quay.io/coreos/etcd:v3.5.2
          name: etcd
          livenessProbe:
            httpGet:
              path: /health
              port: 2379
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 2379
            initialDelaySeconds: 5
            periodSeconds: 10
          # TODO(user): Configure the resources accordingly based on the project requirements.
          # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          ports:
            - containerPort: 2379
              name: etcd
              protocol: TCP
          volumeMounts:
            - name: etcd-data-dir
              mountPath: /etcd-data-dir
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
      terminationGracePeriodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: etcd-data-dir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
