
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.6.2
  creationTimestamp: null
  name: machineclasses.compute.onmetal.de
spec:
  group: compute.onmetal.de
  names:
    kind: MachineClass
    listKind: MachineClassList
    plural: machineclasses
    singular: machineclass
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: MachineClass is the Schema for the machineclasses API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: MachineClassSpec defines the desired state of MachineClass
            properties:
              capabilities:
                description: Capabilities describes the features of the MachineClass
                items:
                  description: Capability describes a single feature of a MachineClass
                  properties:
                    name:
                      description: Name is the name of the capability
                      type: string
                    type:
                      description: Type defines the type of the capability
                      type: string
                    value:
                      description: Value is the effective value of the capability
                      type: string
                  required:
                  - name
                  - type
                  - value
                  type: object
                type: array
            required:
            - capabilities
            type: object
          status:
            description: MachineClassStatus defines the observed state of MachineClass
            properties:
              availability:
                description: Availability describes the regions and zones where this
                  MachineClass is available
                items:
                  description: RegionAvailability defines a region with its availability
                    zones
                  properties:
                    availabilityZones:
                      description: Zones is a list of zones in this region
                      items:
                        description: ZoneAvailability defines the name of a zone
                        properties:
                          name:
                            description: Name is the name of the availability zone
                            type: string
                        required:
                        - name
                        type: object
                      type: array
                    region:
                      description: Region is the name of the region
                      type: string
                  required:
                  - region
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
