
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: machinepools.compute.onmetal.de
spec:
  group: compute.onmetal.de
  names:
    kind: MachinePool
    listKind: MachinePoolList
    plural: machinepools
    singular: machinepool
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.state
      name: StateFields
      type: string
    - jsonPath: .metadata.CreationTimestamp
      name: Age
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: MachinePool is the Schema for the machinepools API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: MachinePoolSpec defines the desired state of MachinePool
            properties:
              capacity:
                description: Capacity defines the quantity of this machine pool per
                  availability zone
                items:
                  description: AvailabilityZoneQuantity defines the quantity of available
                    MachineClasses in a given AZ
                  properties:
                    availabilityZone:
                      description: AvailabilityZone is the name of the availability
                        zone
                      type: string
                    classes:
                      description: Classes defines a list of machine classes and their
                        corresponding quantities
                      items:
                        description: MachineClassQuantity defines the quantity of
                          a given MachineClass
                        properties:
                          name:
                            description: Name is the name of the machine class quantity
                            type: string
                          quantity:
                            description: Quantity is an absolut number of the available
                              machine class
                            minimum: 0
                            type: integer
                        required:
                        - name
                        - quantity
                        type: object
                      type: array
                  required:
                  - availabilityZone
                  - classes
                  type: object
                type: array
              privacy:
                description: Privacy indicates the privacy scope of the machine pool
                type: string
              region:
                description: Region defines the region where this machine pool is
                  available
                type: string
            required:
            - capacity
            - privacy
            type: object
          status:
            description: MachinePoolStatus defines the observed state of MachinePool
            properties:
              message:
                description: Message contains a message for the corresponding state
                type: string
              state:
                description: State indicates the state of a resource
                type: string
              used:
                description: AvailabilityZoneQuantity defines the quantity of available
                  MachineClasses in a given AZ
                properties:
                  availabilityZone:
                    description: AvailabilityZone is the name of the availability
                      zone
                    type: string
                  classes:
                    description: Classes defines a list of machine classes and their
                      corresponding quantities
                    items:
                      description: MachineClassQuantity defines the quantity of a
                        given MachineClass
                      properties:
                        name:
                          description: Name is the name of the machine class quantity
                          type: string
                        quantity:
                          description: Quantity is an absolut number of the available
                            machine class
                          minimum: 0
                          type: integer
                      required:
                      - name
                      - quantity
                      type: object
                    type: array
                required:
                - availabilityZone
                - classes
                type: object
            required:
            - used
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
