
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: images.compute.onmetal.de
spec:
  group: compute.onmetal.de
  names:
    kind: Image
    listKind: ImageList
    plural: images
    singular: image
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.os
      name: OS
      type: string
    - jsonPath: .spec.version
      name: Version
      type: string
    - jsonPath: .spec.maturity
      name: Maturity
      type: string
    - jsonPath: .spec.expirationTime
      name: Expiration
      type: date
    - jsonPath: .spec.type
      name: Type
      priority: 100
      type: string
    - jsonPath: .status.state
      name: StateFields
      type: string
    - jsonPath: .metadata.CreationTimestamp
      name: Age
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Image is the Schema for the images API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ImageSpec defines the desired state of Image
            properties:
              expirationTime:
                description: ExpirationTime defines when the support for this image
                  will expire
                format: date-time
                type: string
              maturity:
                description: Maturity defines the manutiry of an image. It indicates
                  whether this image is e.g. a stable or preview version.
                type: string
              os:
                description: OS defines the operating system name of the image
                type: string
              source:
                description: Source defines the source artefacts and their corresponding
                  location
                items:
                  description: SourceAttribute describes the source components of
                    an Image
                  properties:
                    cmdLine:
                      description: CmdLine defines a Kernel boot command
                      type: string
                    hash:
                      description: Hash is the computed hash value of the artefacts
                        content
                      properties:
                        algorithm:
                          description: Algorithm indicates the algorithm with which
                            the hash should be computed
                          type: string
                        value:
                          description: Value is the computed hash value
                          type: string
                      required:
                      - algorithm
                      - value
                      type: object
                    imageName:
                      description: ImageName defines the name of a referred image
                      type: string
                    name:
                      description: Name defines the name of a source element
                      type: string
                    url:
                      description: URL defines the location of the image artefact
                      type: string
                  required:
                  - name
                  type: object
                type: array
              type:
                description: Type specifies the type of the image
                type: string
              version:
                description: Version defines the operating system version
                type: string
            required:
            - maturity
            - os
            - source
            - version
            type: object
          status:
            description: ImageStatus defines the observed state of Image
            properties:
              hashes:
                description: Hashes lists all hashes for all included artefacts
                items:
                  properties:
                    hash:
                      type: string
                    name:
                      type: string
                  required:
                  - hash
                  - name
                  type: object
                type: array
              message:
                description: Message contains a message for the corresponding state
                type: string
              regions:
                description: Regions indicates the availability of the image in the
                  corresponding regions
                items:
                  properties:
                    message:
                      description: Message contains a message for the corresponding
                        state
                      type: string
                    name:
                      type: string
                    state:
                      description: State indicates the state of a resource
                      type: string
                  required:
                  - name
                  type: object
                type: array
              state:
                description: State indicates the state of a resource
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
