
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: reservedips.network.onmetal.de
spec:
  group: network.onmetal.de
  names:
    kind: ReservedIP
    listKind: ReservedIPList
    plural: reservedips
    singular: reservedip
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.ip
      name: IP
      type: string
    - jsonPath: .status.state
      name: StateFields
      type: string
    - jsonPath: .metadata.CreationTimestamp
      name: Age
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ReservedIP is the Schema for the reservedips API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ReservedIPSpec defines the desired state of ReservedIP
            properties:
              assignment:
                description: Assignment indicates to which resource this IP address
                  should be assigned
                properties:
                  apigroup:
                    description: APIGroup is the API group of the assigned resource
                    type: string
                  kind:
                    description: Kind is the object kind of the assigned resource
                    type: string
                  name:
                    description: Name is the name of the scope
                    type: string
                  scope:
                    description: Scope is the absolute scope path
                    type: string
                required:
                - apigroup
                - kind
                - name
                - scope
                type: object
              ip:
                description: IP specifies an IP address which should be reserved.
                  Must be in the CIDR of the associated Subnet
                type: string
              subnet:
                description: Subnet references the subnet where an IP address should
                  be reserved
                properties:
                  name:
                    description: Name is the name of the scope
                    type: string
                  scope:
                    description: Scope is the absolute scope path
                    type: string
                required:
                - name
                - scope
                type: object
            required:
            - subnet
            type: object
          status:
            description: ReservedIPStatus defines the observed state of ReservedIP
            properties:
              ip:
                description: IP indicates the effective reserved IP address
                type: string
              message:
                description: Message contains a message for the corresponding state
                type: string
              state:
                description: State indicates the state of a resource
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
