
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: securitygroups.network.onmetal.de
spec:
  group: network.onmetal.de
  names:
    kind: SecurityGroup
    listKind: SecurityGroupList
    plural: securitygroups
    singular: securitygroup
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.state
      name: StateFields
      type: string
    - jsonPath: .metadata.CreationTimestamp
      name: Age
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: SecurityGroup is the Schema for the securitygroups API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: SecurityGroupSpec defines the desired state of SecurityGroup
            properties:
              egress:
                description: Egress is a list of outbound rules
                items:
                  description: EgressSecurityGroupRule is an egress rule of a security
                    group
                  properties:
                    action:
                      description: Action defines the action type of a SecurityGroupRule
                      type: string
                    destination:
                      description: Destination is either the cird or a reference to
                        another security group
                      properties:
                        cidr:
                          description: CIDR block for source/destination
                          type: string
                        securitygroupref:
                          description: SecurityGroupRef references a security group
                          properties:
                            name:
                              description: Name is the name of the scope
                              type: string
                            scope:
                              description: Scope is the absolute scope path
                              type: string
                          required:
                          - name
                          - scope
                          type: object
                      type: object
                    name:
                      description: Name is the name of the SecurityGroupRule
                      type: string
                    portrange:
                      description: PortRange is the port range of the SecurityGroupRule
                      properties:
                        endport:
                          description: EndPort is the end port of the port range
                          type: integer
                        startport:
                          description: StartPort is the start port of the port range
                          type: integer
                      required:
                      - endport
                      - startport
                      type: object
                    protocol:
                      description: Protocol defines the protocol of a SecurityGroupRule
                      type: string
                    securitygroupref:
                      description: SecurityGroupRef is a scoped reference to an existing
                        SecurityGroup
                      properties:
                        name:
                          description: Name is the name of the scope
                          type: string
                        scope:
                          description: Scope is the absolute scope path
                          type: string
                      required:
                      - name
                      - scope
                      type: object
                  required:
                  - name
                  type: object
                type: array
              ingress:
                description: Ingress is a list of inbound rules
                items:
                  description: IngressSecurityGroupRule is an ingress rule of a security
                    group
                  properties:
                    action:
                      description: Action defines the action type of a SecurityGroupRule
                      type: string
                    name:
                      description: Name is the name of the SecurityGroupRule
                      type: string
                    portrange:
                      description: PortRange is the port range of the SecurityGroupRule
                      properties:
                        endport:
                          description: EndPort is the end port of the port range
                          type: integer
                        startport:
                          description: StartPort is the start port of the port range
                          type: integer
                      required:
                      - endport
                      - startport
                      type: object
                    protocol:
                      description: Protocol defines the protocol of a SecurityGroupRule
                      type: string
                    securitygroupref:
                      description: SecurityGroupRef is a scoped reference to an existing
                        SecurityGroup
                      properties:
                        name:
                          description: Name is the name of the scope
                          type: string
                        scope:
                          description: Scope is the absolute scope path
                          type: string
                      required:
                      - name
                      - scope
                      type: object
                    source:
                      description: Source is either the cird or a reference to another
                        security group
                      properties:
                        cidr:
                          description: CIDR block for source/destination
                          type: string
                        securitygroupref:
                          description: SecurityGroupRef references a security group
                          properties:
                            name:
                              description: Name is the name of the scope
                              type: string
                            scope:
                              description: Scope is the absolute scope path
                              type: string
                          required:
                          - name
                          - scope
                          type: object
                      type: object
                  required:
                  - name
                  type: object
                type: array
            type: object
          status:
            description: SecurityGroupStatus defines the observed state of SecurityGroup
            properties:
              message:
                description: Message contains a message for the corresponding state
                type: string
              state:
                description: State indicates the state of a resource
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
