
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: subnetips.network.onmetal.de
spec:
  group: network.onmetal.de
  names:
    kind: SubnetIP
    listKind: SubnetIPList
    plural: subnetips
    singular: subnetip
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.ip
      name: IP
      type: string
    - jsonPath: .spec.subnet.name
      name: Subnet
      type: string
    - jsonPath: .spec.subnet.scope
      name: SubnetScope
      type: string
    - jsonPath: .spec.target.name
      name: Target
      type: string
    - jsonPath: .spec.target.kind
      name: TargetKind
      type: string
    - jsonPath: .status.state
      name: StateFields
      type: string
    - jsonPath: .metadata.CreationTimestamp
      name: Age
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: SubnetIP is the Schema for the subnetips API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: SubnetIPSpec defines the desired state of SubnetIP
            properties:
              ip:
                description: IP is the used IP in a given subnet
                format: byte
                type: string
              subnet:
                description: Subnet is the subnet of the IP
                properties:
                  name:
                    description: Name is the name of the scope
                    type: string
                  scope:
                    description: Scope is the absolute scope path
                    type: string
                required:
                - name
                - scope
                type: object
              target:
                description: Target is the resource the IP is assigned to
                properties:
                  apigroup:
                    description: APIGroup is the API group of the object
                    type: string
                  kind:
                    description: Kind is the kind of the object
                    type: string
                  name:
                    description: Name is the name of the scope
                    type: string
                  scope:
                    description: Scope is the absolute scope path
                    type: string
                required:
                - apigroup
                - kind
                - name
                - scope
                type: object
            required:
            - ip
            - subnet
            - target
            type: object
          status:
            description: SubnetIPStatus defines the observed state of SubnetIP
            properties:
              message:
                description: Message contains a message for the corresponding state
                type: string
              state:
                description: State indicates the state of a resource
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
