
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: storagepools.storage.onmetal.de
spec:
  group: storage.onmetal.de
  names:
    kind: StoragePool
    listKind: StoragePoolList
    plural: storagepools
    singular: storagepool
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.state
      name: StateFields
      type: string
    - jsonPath: .metadata.CreationTimestamp
      name: Age
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: StoragePool is the Schema for the storagepools API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: StoragePoolSpec defines the desired state of StoragePool
            properties:
              capacity:
                description: Capacity list the available capacity of a storage pool
                items:
                  description: StorageClassCapacity defines capacity attribute of
                    a storage class
                  properties:
                    capacity:
                      anyOf:
                      - type: integer
                      - type: string
                      description: Capacity is the quantity of a capacity
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                    name:
                      description: Name is the name of a storage class capacity
                      type: string
                  required:
                  - name
                  type: object
                type: array
              privacy:
                description: Privacy defines the privacy scope of the storage pool
                type: string
              region:
                description: Region defines the region of the storage pool
                type: string
              replication:
                description: Replication indicates the replication factor in the storage
                  pool
                minimum: 0
                type: integer
            required:
            - privacy
            type: object
          status:
            description: StoragePoolStatus defines the observed state of StoragePool
            properties:
              message:
                description: Message contains a message for the corresponding state
                type: string
              state:
                description: State indicates the state of a resource
                type: string
              used:
                description: Used indicates how much capacity has been used in a storage
                  pool
                items:
                  description: StorageClassCapacity defines capacity attribute of
                    a storage class
                  properties:
                    capacity:
                      anyOf:
                      - type: integer
                      - type: string
                      description: Capacity is the quantity of a capacity
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                    name:
                      description: Name is the name of a storage class capacity
                      type: string
                  required:
                  - name
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
