name: Size Label

on: pull_request

jobs:
  size-label:
    runs-on: self-hosted
    steps:
      - name: size-label
        uses: pascalgn/size-label-action@v0.4.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
